### PR TITLE
fix(types): allow readstream and buffer in payload

### PR DESCRIPTION
**Pull request by bitomic**
The type only allows `string` in `Payload['image']`, but a `ReadStream` works too and it is even used in the example in the repo's README. However, TypeScript will complain because type `ReadStream` is not assignable to type `string`.

### CODE REVIEW

**Comment by bitomic** [comment]
Just tested and a buffer works too:
```ts
import fetch from 'node-fetch'
import { ImgurClient } from 'imgur'

( async () => {
	const client = new ImgurClient( {
		clientId: 'imgur id'
	} )
	const req = await fetch( 'URL to image' )
	const image = await req.buffer()
	console.log( await client.upload( {
		image: image
	} ) )
} )()
```

**Comment by KenEucker** [comment]
Thanks for the PR, @bitomic!

This project builds an isomorphic library, so the use of fs.ReadStream should not be used, but stream.Readable instead. I have incorporated these changes in my recent push to the develop branch and I will include it in the next release (2.0.2).

**Comment by bitomic** [comment]
Oh, cool! Thank you, I'll be waiting for it to remove the `// @ts-expect-error` comments in my project haha.

**Comment by KenEucker** [comment]
I have no reason to wait. I'll publish it now and then you can let me know if you have any further issues!

**Pull request closed without merging**
